repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        exclude: ^zemfrog_test/templates/
        args: ["-v"]

-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        exclude: ^zemfrog_test/templates/
        args: ["-v", "--df"]

-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        exclude: ^zemfrog_test/templates/
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]
